export const volumes = [
  { slug:"whole-body-presence", num:"I", glyph:"🜂", title:"Whole Body Presence", element:"Fire", solid:"Tetrahedron", mantra:"The instrument comes first.", description:"Tune the body before you tune the world. A field manual for embodied attention, clean action, and presence that holds under pressure.", excerpt:"Before you build a life, build the instrument that will live it. The body is not a vehicle for the mind. It is the first architecture.\nPresence is not stillness. It is total participation: every sense awake, every signal received, no part of you abandoned at the threshold.", digital:27, physical:74, status:"Pre-order" },
  { slug:"twelvefold-harmonics", num:"II", glyph:"🜁", title:"Twelvefold Harmonics", element:"Air", solid:"Octahedron", mantra:"Pattern communicates across scales.", description:"Twelve frequencies. One system. A practical study of pattern, proportion, resonance, and the invisible structures that organize living work.", excerpt:"A pattern is not an image repeated. It is a relationship kept alive. Twelvefold order appears wherever difference learns to cooperate.\nThe signal moves through breath, room, season, exchange. You do not command it. You become clear enough to carry it.", digital:27, physical:74, status:"Pre-order" },
  { slug:"infinite-presence", num:"III", glyph:"🜄", title:"Infinite Presence", element:"Water", solid:"Icosahedron", mantra:"Presence without boundary.", description:"The shape of water and the practice of staying whole while moving through change, intimacy, grief, and creation.", excerpt:"Water does not confuse surrender with disappearance. It yields without leaving itself. It enters every shape and remains water.\nTo become infinitely present is not to occupy all space. It is to stop refusing the space you already touch.", digital:27, physical:74, status:"Pre-order" },
  { slug:"the-ground", num:"IV", glyph:"🜃", title:"The Ground", element:"Earth", solid:"Cube", mantra:"Structure outlasts you.", description:"A forthcoming volume on land, structure, stewardship, and building physical systems designed to remain.", excerpt:"The ground remembers every structure placed upon it. Build as if the memory matters.\nWhat holds you should also hold the ones who arrive after you.", digital:27, physical:74, status:"Forthcoming" },
  { slug:"the-gate", num:"V", glyph:"☉", title:"The Gate", element:"Ether", solid:"Dodecahedron", mantra:"The final frequency.", description:"The final volume in the series. A forthcoming work on integration, passage, and the architecture beyond the threshold.", excerpt:"Every complete system contains a door. The door is not an escape. It is the moment the system becomes capable of giving itself away.", digital:27, physical:74, status:"Forthcoming" },
] as const;

export type Volume = (typeof volumes)[number];
