import Link from "next/link";
import { Reveal } from "../components/Reveal";
import FloatingTetrahedronGarden from "../components/models/FloatingTetrahedronGarden";
import FloatingQuincunxDome from "../components/models/FloatingQuincunxDome";
import FloatingGreatHall from "../components/models/FloatingGreatHall";
import FloatingLivingRiver from "../components/models/FloatingLivingRiver";
import FloatingPrismCathedral from "../components/models/FloatingPrismCathedral";

const phases=[["01","THE TRIANGLE","Land, water, power, food, and temporary shelter establish the survival baseline."],["02","THE QUINCUNX","Permanent homes and training grounds let the village breathe."],["03","THE NONAGON","The recording studio, great hall, and publishing systems give the village a voice."],["04","THE DODECAHEDRON","The complete settlement becomes a pattern that can seed new ground."]];
export default function BuildPage(){return <div className="page-wrap model-page"><header className="page-hero"><p className="eyebrow">GEOMETRIC EXPANSION / 01</p><h1>THE BUILD SEQUENCE</h1><p>We establish the survival baseline first, then expand only when the land and people can hold the next layer.</p></header><Reveal><FloatingTetrahedronGarden disableAutoRotate height="480px" /></Reveal><section className="model-section"><Reveal><p className="eyebrow">PHASE 1 / SURVIVAL BASELINE</p><h2>THE RIVER<br/>COMES FIRST.</h2><p>Before permanent shelter expands, the well, storage, filtration, pond, irrigation, and return loop must work as one gravity-led circulatory system.</p></Reveal><Reveal delay={.1}><FloatingLivingRiver disableAutoRotate height="540px"/></Reveal></section><section id="quincunx" className="model-section"><Reveal><p className="eyebrow">PHASE 2 / THE QUINCUNX</p><h2>FOUR DOMES.<br/>ONE CENTER.</h2><p>Earth, Fire, Air, and Water occupy the four corners. The copper Observer at center connects all four through the quincunx axes.</p></Reveal><Reveal delay={.1}><FloatingQuincunxDome height="600px" /></Reveal></section><section id="great-hall" className="model-section"><Reveal><p className="eyebrow">PHASE 3–4 / THE GREAT HALL</p><h2>GEOMETRY<br/>BECOMES ACOUSTICS.</h2><p>The nonagonal base organizes the gathering. The twelve-faced ceiling tunes the room. Sound waves travel from the central stage while the mast carries the village voice outward.</p></Reveal><Reveal delay={.1}><FloatingGreatHall height="640px" /></Reveal></section><section id="cathedral" className="model-section"><Reveal><p className="eyebrow">PHASE 4 / THE PRISM CATHEDRAL</p><h2>THE FINAL<br/>GATE OPENS.</h2><p>The dodecahedral culmination joins twelve prismatic faces, thirty copper edges, a Flower of Life floor, standing stones, and a central light beam into one resonant structure.</p></Reveal><Reveal delay={.1}><FloatingPrismCathedral height="680px"/></Reveal></section><div className="build-phases">{phases.map(([n,title,text],i)=><Reveal key={n} delay={i*.05}><article><span>{n}</span><h2>{title}</h2><p>{text}</p></article></Reveal>)}</div><div className="page-cta"><Link href="/foundation/apply" className="button primary">Apply to Build →</Link></div></div>}
