import Link from "next/link";
import { notFound } from "next/navigation";
import { Reveal } from "../components/Reveal";

const pages: Record<string, { eyebrow: string; title: string; intro: string; sections: { title: string; text: string; items?: string[] }[] }> = {
  "the-build": { eyebrow: "GEOMETRIC EXPANSION / 01", title: "THE BUILD SEQUENCE", intro: "We do not build a subdivision. We establish the survival baseline, then expand only when the land and people can hold the next layer.", sections: [
    { title: "THE TRIANGLE", text: "Land, water, power and food come first.", items: ["Land held in trust", "Well, cistern and solar pump", "Twelve-bed garden and greenhouse", "Temporary builder shelter", "Independent power and communications"] },
    { title: "THE QUINCUNX", text: "Permanent homes and learning spaces bring the village online.", items: ["Clover homes", "Elemental training grounds", "Retreat capacity", "Expanded water return system"] },
    { title: "THE NONAGON", text: "The village gains a voice.", items: ["Recording studio", "Great hall", "Publishing and broadcast", "Working economic engine"] },
    { title: "THE DODECAHEDRON", text: "The complete pattern becomes repeatable.", items: ["Full village infrastructure", "Acoustic gathering space", "Protected governance", "Seed-community protocol"] }] },
  "the-land": { eyebrow: "SITE SEARCH / 02", title: "THE LAND", intro: "We are searching the Morongo Valley and Landers corridor for high-desert ground with workable access, water rights, solar exposure and room to grow.", sections: [{ title: "SELECTION CRITERIA", text: "The site must be beautiful, but beauty is not enough.", items: ["Ten to twenty usable acres", "Verified legal access", "Water feasibility and clear mineral rights", "Southern solar exposure", "Buildable soils and responsible drainage", "Distance from incompatible development"] }, { title: "CURRENT STATUS", text: "Phase 0 is active. Candidate parcels are being evaluated before any public commitment is made." }] },
  "the-river": { eyebrow: "CLOSED LOOP WATER / 03", title: "THE LIVING RIVER", intro: "Water moves from source to storage, treatment, people, soil and back again. The goal is a visible system that can be tested, repaired and understood.", sections: [{ title: "THE COMPLETE LOOP", text: "Well → Cistern → Copper Contact → Filtration → Distribution → Greywater Return" }, { title: "WHY COPPER", text: "Copper is durable, highly conductive and naturally antimicrobial. All potable-water decisions will follow testing, code and engineering review." }, { title: "WHY VORTEX", text: "Vortex treatment is an experimental layer inspired by natural flow. We will test outcomes and publish what the water actually shows." }] },
  "the-garden": { eyebrow: "FOOD SOVEREIGNTY / 04", title: "THE TETRAHEDRON GARDEN", intro: "Twelve raised beds form a radial growing system calibrated to the high-desert sun, with cold frames and protected cultivation extending the season.", sections: [{ title: "GROW WITH THE SITE", text: "A garden should reveal conditions, not fight them.", items: ["Twelve raised beds", "Solar-calibrated central gnomon", "Cold frames for shoulder seasons", "Greenhouse for protected crops", "Orchard tied to greywater return", "Native windbreak and pollinator habitat"] }, { title: "MEASURE EVERYTHING", text: "Soil, water, yield and season-extension results will become a practical record for future sites." }] },
  homes: { eyebrow: "SHELTER SYSTEM / 05", title: "CLOVER HOMES", intro: "Compact, durable homes organized around light, shade and shared infrastructure—designed for low operating demand and a fast, legible build sequence.", sections: [{ title: "THE PROTOTYPE", text: "A four-lobed plan creates distinct living zones around a central daylit core.", items: ["Structural insulated shell", "High-desert passive design", "Living roof where conditions allow", "Independent solar readiness", "Accessible wet core", "Repairable material palette"] }, { title: "OWN THE LABOR", text: "The community holds the land. Residents retain the value of their work through clear agreements and protected stewardship rights." }] },
  about: { eyebrow: "WHO WE ARE / 06", title: "FOUNDATION", intro: "Whole Body Foundation is the physical arm of a larger creative ecosystem: land, water, food, shelter and gathering space built to keep cultural work rooted.", sections: [{ title: "PLAIN ENGLISH", text: "This is a land project in its earliest phase. It is not a finished village, an available housing program or a guarantee of future residency." }, { title: "THE COMMITMENT", text: "Build slowly enough to remain honest. Share what works. Protect the ground from extraction. Let the infrastructure serve the people who maintain it." }] },
  support: { eyebrow: "SUPPORT / 07", title: "HELP HOLD THE GROUND", intro: "Support can take the form of materials, professional services, introductions, field research or patient capital conversations.", sections: [{ title: "WHAT HELPS NOW", text: "Phase 0 support strengthens land review and technical diligence.", items: ["Surveying and civil engineering", "Water-rights research", "Soil and geotechnical analysis", "Permitting guidance", "Regenerative landscape design", "Introductions to aligned landowners"] }, { title: "START A CONVERSATION", text: "Public pages do not list capital terms. Contact us for a private, documented conversation." }] },
  contact: { eyebrow: "CONTACT / 08", title: "OPEN A CHANNEL", intro: "Tell us what you build, what you know, and why this ground matters to you.", sections: [{ title: "GENERAL INQUIRIES", text: "For land leads, professional support, press and aligned partnerships, begin with a concise note." }] }
};

export default async function ContentPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = pages[slug]; if (!page) notFound(); return <div className="page-wrap"><header className="page-hero"><p className="eyebrow">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p></header><div className="content-stack">{page.sections.map((section,i)=><Reveal key={section.title} delay={i*.05}><section className="content-card"><span>0{i+1}</span><h2>{section.title}</h2><p>{section.text}</p>{section.items && <ul>{section.items.map(item=><li key={item}>▸ {item}</li>)}</ul>}</section></Reveal>)}</div><div className="page-cta"><Link href={slug === "contact" ? "/foundation/apply" : "/foundation/apply"} className="button primary">{slug === "support" ? "Start a Conversation" : "Apply to Build"} →</Link></div></div>; }
