"use client";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { Edges } from "@react-three/drei";
import * as THREE from "three";
import { type DomeConfig,DOME_SPECS } from "./quincunx-data";

export default function ElementalDome({config,index}:{config:DomeConfig;index:number}){const light=useRef<THREE.PointLight>(null);useFrame(({clock})=>{if(light.current)light.current.intensity=.5+Math.sin(clock.elapsedTime*.6+index*1.5)*.15});const r=DOME_SPECS.diameter/2;return <group position={config.position}>
 <mesh position={[0,-.05,0]} receiveShadow><cylinderGeometry args={[r+.15,r+.2,.1,32]}/><meshStandardMaterial color="#2a2a28" roughness={.95}/><Edges color="#30372b"/></mesh>
 <mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[r-.05,32]}/><meshStandardMaterial color={config.bodyColor} emissive={config.emissiveColor} emissiveIntensity={.3} roughness={.8}/></mesh>
 <mesh castShadow><sphereGeometry args={[r,16,8,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color={config.bodyColor} emissive={config.emissiveColor} emissiveIntensity={.1} transparent opacity={DOME_SPECS.wallOpacity} roughness={.4} metalness={.2} side={THREE.DoubleSide}/><Edges color={config.accentColor}/></mesh>
 <mesh><sphereGeometry args={[r+.01,12,8,0,Math.PI*2,0,Math.PI/2]}/><meshBasicMaterial color={config.accentColor} wireframe transparent opacity={.18}/></mesh>
 <mesh position={[0,.45,0]} rotation={[0,Math.atan2(-config.position[0],-config.position[2]),0]}><boxGeometry args={[.5,.8,.02]}/><meshStandardMaterial color="#050604" emissive={config.accentColor} emissiveIntensity={.05}/></mesh>
 <mesh position={[0,1.14,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.08,.12,16]}/><meshStandardMaterial color={config.accentColor} emissive={config.accentColor} emissiveIntensity={.3} side={THREE.DoubleSide}/></mesh>
 <pointLight ref={light} position={[0,.4,0]} color={config.accentColor} distance={r*1.7} decay={2}/><Interior element={config.element}/>
 </group>}
function Interior({element}:{element:DomeConfig["element"]}){if(element==="earth")return <group position={[0,.2,0]}><mesh><cylinderGeometry args={[.15,.18,.3,8]}/><meshStandardMaterial color="#2a2a28"/></mesh><mesh position={[0,.28,0]} castShadow><boxGeometry args={[.28,.28,.28]}/><meshStandardMaterial color="#b87333" emissive="#8b5a2b" emissiveIntensity={.2} metalness={.7}/><Edges color="#84a66e"/></mesh></group>;if(element==="fire")return <group position={[0,.2,0]}><mesh><cylinderGeometry args={[.2,.25,.2,8]}/><meshStandardMaterial color="#2a2a28"/></mesh><Flame/></group>;if(element==="air")return <group position={[0,.2,0]}><mesh><cylinderGeometry args={[.04,.06,.3,6]}/><meshStandardMaterial color="#2a2a28"/></mesh><AirSphere/></group>;return <group position={[0,.2,0]}><mesh><cylinderGeometry args={[.22,.18,.15,16]}/><meshStandardMaterial color="#1a2a24" metalness={.6}/><Edges color="#84a66e"/></mesh><mesh position={[0,.08,0]}><cylinderGeometry args={[.2,.2,.01,16]}/><meshStandardMaterial color="#84a66e" transparent opacity={.45} emissive="#84a66e" emissiveIntensity={.22} metalness={.8}/></mesh></group>}
function Flame(){const r=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(r.current){r.current.scale.y=1+Math.sin(clock.elapsedTime*8)*.15;r.current.scale.x=1+Math.cos(clock.elapsedTime*6)*.08;r.current.rotation.y=clock.elapsedTime*.5}});return <mesh ref={r} position={[0,.35,0]}><coneGeometry args={[.1,.35,6]}/><meshStandardMaterial color="#b87333" emissive="#8b3b1d" emissiveIntensity={.85} transparent opacity={.78}/></mesh>}
function AirSphere(){const r=useRef<THREE.Group>(null);useFrame(({clock})=>{if(r.current){r.current.position.y=.35+Math.sin(clock.elapsedTime*1.5)*.08;r.current.rotation.y=clock.elapsedTime*.3;r.current.rotation.x=clock.elapsedTime*.15}});return <group ref={r}><mesh><sphereGeometry args={[.12,16,16]}/><meshStandardMaterial color="#84a66e" emissive="#526744" emissiveIntensity={.2} metalness={.7} transparent opacity={.7}/></mesh><mesh><sphereGeometry args={[.16,8,8]}/><meshBasicMaterial color="#84a66e" wireframe transparent opacity={.25}/></mesh></group>}
