import { PILLARS, type PillarId } from "@/lib/pillars";
import { eventDateTime, eventHref, eventPrice, getPublicEvents } from "@/lib/events";
import Link from "next/link";

export const dynamic = "force-dynamic";

export default async function EventsPage() {
  const events = await getPublicEvents();
  return <main className="px-6 py-16 md:py-24"><div className="mx-auto max-w-[1200px]"><header className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-press">Gatherings</p><h1 className="mt-5 font-display text-5xl leading-[.94] text-bone sm:text-6xl">Events across the <span className="text-press">Constellation.</span></h1><p className="mt-6 text-lg leading-8 text-ghost">Circles, releases, garden days, listening rooms, and practical work—held in one living calendar.</p></header><section className="mt-12"><div className="flex items-end justify-between gap-5 border-b border-mercury pb-4"><div><p className="font-mono text-[10px] uppercase tracking-[.15em] text-ghost">Upcoming events</p><p className="mt-2 text-sm text-ghost">Every listing is a live calendar record with its own availability.</p></div><span className="font-mono text-xs text-press">{events.length} scheduled</span></div>{events.length ? <div className="divide-y divide-mercury">{events.map((event) => { const pillar = PILLARS[event.pillar as PillarId]; return <article key={event.id} className="grid gap-5 py-7 md:grid-cols-[10rem_minmax(0,1fr)_auto] md:items-center"><div className="font-mono text-xs uppercase tracking-[.13em]" style={{ color: pillar?.color ?? "var(--bone)" }}>{pillar?.symbol ?? "✦"} {pillar?.name ?? event.pillar}</div><div><p className="font-mono text-[10px] uppercase tracking-[.13em] text-ghost">{eventDateTime(event)}{event.recurring ? ` · Every ${event.recurring}` : ""}</p><h2 className="mt-2 font-display text-3xl text-bone">{event.title}</h2><p className="mt-2 text-sm leading-6 text-ghost">{event.location ?? (event.locationType === "virtual" ? "Virtual" : "Whole Body Earth")} · {eventPrice(event)}{event.spotsRemaining !== null ? ` · ${event.spotsRemaining} spots left` : ""}</p></div><Link href={eventHref(event)} className="border px-4 py-3 text-center font-mono text-[10px] uppercase tracking-[.12em] transition hover:bg-white/10" style={{ borderColor: pillar?.color ?? "var(--mercury)", color: pillar?.color ?? "var(--bone)" }}>View & reserve →</Link></article>; })}</div> : <div className="mt-8 border border-mercury bg-carbon/55 p-8 text-center"><p className="font-display text-2xl text-bone">The next gathering is forming.</p><p className="mt-3 text-sm text-ghost">Check back soon, or open the live shelf for activity across the five pillars.</p></div>}</section></div></main>;
}
