import Link from "next/link";
import { PILLARS, type PillarId } from "@/lib/pillars";

const JOURNEYS: Record<PillarId, Array<{ label: string; href: string; note: string }>> = {
  presence: [{ label: "Gatherings", href: "/pillars/presence/gatherings", note: "Weekly, monthly, seasonal" }, { label: "Men", href: "/pillars/presence/men", note: "A closed forge" }, { label: "Women", href: "/pillars/presence/women", note: "A closed hearth" }, { label: "Retreats", href: "/pillars/presence/retreats", note: "In-person return" }, { label: "About", href: "/pillars/presence/about", note: "The return to the circle" }],
  press: [{ label: "Library", href: "/pillars/press/library", note: "All five volumes" }, { label: "Reading paths", href: "/pillars/press/collections", note: "Choose your entrance" }, { label: "Reader portal", href: "/pillars/press/readers", note: "Your permanent shelf" }, { label: "Submissions", href: "/pillars/press/submissions", note: "For aligned authors" }, { label: "About", href: "/pillars/press/about", note: "The publishing code" }],
  studios: [{ label: "Catalog", href: "/pillars/studios/catalog", note: "Current work and releases" }, { label: "Services", href: "/pillars/studios/services", note: "Production infrastructure" }, { label: "Calendar", href: "/events", note: "Sessions and releases" }, { label: "Apply", href: "/apply", note: "Bring your work" }, { label: "About", href: "/pillars/studios/about", note: "The operating model" }],
  foundation: [{ label: "Garden", href: "/pillars/foundation/garden", note: "Phase 1 · active now" }, { label: "Dome", href: "/pillars/foundation/dome", note: "Phase 2 · in design" }, { label: "Visit", href: "/pillars/foundation/visit", note: "Guided walks" }, { label: "Waitlist", href: "/pillars/foundation/waitlist", note: "Build with us" }, { label: "About", href: "/pillars/foundation/about", note: "The ground beneath it" }],
  guardian: [{ label: "Observer seat", href: "/pillars/guardian/quincunx", note: "Position 9 · Ø" }, { label: "Manifesto", href: "/pillars/guardian/manifesto", note: "Read the code" }, { label: "Partners", href: "/pillars/guardian/partners", note: "Curated and verified" }, { label: "About", href: "/pillars/guardian/about", note: "The final layer" }],
};

export function PillarJourneyMap({ pillar: id }: { pillar: PillarId }) {
  const pillar = PILLARS[id];
  return <section className="mt-20 border-t pt-8" style={{ borderColor: `${pillar.color}55` }}><div className="flex flex-wrap items-baseline justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[.18em]" style={{ color: pillar.color }}>Continue the journey</p><h2 className="mt-2 font-display text-3xl text-bone">Choose your next door.</h2></div><Link href={pillar.href} className="font-mono text-xs uppercase tracking-[.12em]" style={{ color: pillar.color }}>Pillar home →</Link></div><div className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-mercury bg-mercury sm:grid-cols-2 lg:grid-cols-5">{JOURNEYS[id].map((item) => <Link key={item.href} href={item.href} className="bg-carbon p-4 transition hover:bg-steel"><p className="font-mono text-xs uppercase tracking-[.12em]" style={{ color: pillar.color }}>{item.label}</p><p className="mt-2 text-sm text-ghost">{item.note}</p></Link>)}</div></section>;
}
