"use client";
import { useRef } from "react";import { useFrame } from "@react-three/fiber";import { Edges } from "@react-three/drei";import type { PointLight } from "three";import { ANTENNA_SEGMENTS,HALL_HEIGHT,NONAGON_RADIUS,NONAGON_SIDES,PILLARS } from "./great-hall-data";import ConcentricSeats from "./ConcentricSeats";import SoundWaveField from "./SoundWaveField";import AcousticDome from "./AcousticDome";
export default function GreatHallScene(){const beacon=useRef<PointLight>(null);useFrame(({clock})=>{if(beacon.current)beacon.current.intensity=.25+Math.max(0,Math.sin(clock.elapsedTime*2.2))*.7});return <group><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.21,0]} receiveShadow><circleGeometry args={[NONAGON_RADIUS+3,48]}/><meshStandardMaterial color="#0b0d09" roughness={1}/></mesh><mesh rotation={[-Math.PI/2,0,0]}><circleGeometry args={[NONAGON_RADIUS-.15,NONAGON_SIDES]}/><meshStandardMaterial color="#3a2a1a" emissive="#1a0f00" emissiveIntensity={.05} roughness={.6}/></mesh>
 {Array.from({length:9},(_,i)=>{const a=i/9*Math.PI*2;return <group key={i}><mesh position={[Math.cos(a)*2.49,HALL_HEIGHT/2,Math.sin(a)*2.49]} rotation={[0,-a,0]}><boxGeometry args={[1.72,HALL_HEIGHT,.06]}/><meshStandardMaterial color="#2a2a28" transparent opacity={.34} roughness={.82}/><Edges color="#30372b"/></mesh><mesh position={[0,.008,0]} rotation={[-Math.PI/2,0,a]}><planeGeometry args={[.018,2.2]}/><meshBasicMaterial color="#b87333" transparent opacity={.2}/></mesh></group>})}
 {PILLARS.map(p=><group key={p.index} position={p.position}><mesh position={[0,HALL_HEIGHT/2,0]}><cylinderGeometry args={[.08,.1,HALL_HEIGHT,8]}/><meshStandardMaterial color="#2a2a28" roughness={.85}/><Edges color="#30372b"/></mesh><mesh position={[0,HALL_HEIGHT+.05,0]}><boxGeometry args={[.24,.1,.24]}/><meshStandardMaterial color="#b87333" emissive="#8b5a2b" emissiveIntensity={.12} metalness={.85}/></mesh></group>)}
 <ConcentricSeats/><group><mesh position={[0,.08,0]}><cylinderGeometry args={[.5,.55,.15,16]}/><meshStandardMaterial color="#3a2a1a" emissive="#1a0f00" emissiveIntensity={.08}/><Edges color="#84a66e"/></mesh><mesh position={[0,.16,0]}><torusGeometry args={[.5,.015,8,32]}/><meshStandardMaterial color="#b87333" emissive="#8b5a2b" emissiveIntensity={.2} metalness={.9}/></mesh><mesh position={[0,.166,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.08,16]}/><meshStandardMaterial color="#84a66e" emissive="#84a66e" emissiveIntensity={.45}/></mesh></group><SoundWaveField/><AcousticDome/>
 <group position={[0,HALL_HEIGHT+2.25,0]}>{ANTENNA_SEGMENTS.map((s,i)=><mesh key={i} position={[0,s.y+s.height/2,0]}><cylinderGeometry args={[s.radius,s.radius*1.2,s.height,8]}/><meshStandardMaterial color="#b87333" emissive="#8b5a2b" emissiveIntensity={.12} metalness={.9}/></mesh>)}<mesh position={[0,1.35,0]}><sphereGeometry args={[.055,12,12]}/><meshStandardMaterial color="#84a66e" emissive="#84a66e" emissiveIntensity={1}/></mesh><pointLight ref={beacon} position={[0,1.35,0]} color="#84a66e" distance={4}/></group>
 <group position={[0,.6,NONAGON_RADIUS]}><mesh><boxGeometry args={[1.05,1.35,.12]}/><meshStandardMaterial color="#11140e" transparent opacity={.7}/><Edges color="#b87333"/></mesh><mesh position={[-.27,0,.07]}><boxGeometry args={[.48,1.15,.04]}/><meshStandardMaterial color="#84a66e" transparent opacity={.16}/></mesh><mesh position={[.27,0,.07]}><boxGeometry args={[.48,1.15,.04]}/><meshStandardMaterial color="#84a66e" transparent opacity={.16}/></mesh></group>{[0,1,2].map(i=><mesh key={i} position={[0,-.15-i*.08,NONAGON_RADIUS+.5+i*.35]}><boxGeometry args={[1.2-i*.2,.08,.35]}/><meshStandardMaterial color="#2a2a28"/><Edges color="#30372b"/></mesh>)}
 <directionalLight position={[6,10,4]} intensity={1} color="#d8e3ce" castShadow shadow-mapSize-width={1024} shadow-mapSize-height={1024}/><pointLight position={[0,1,NONAGON_RADIUS+2]} intensity={.35} color="#b87333"/><pointLight position={[-4,3,-4]} intensity={.4} color="#84a66e"/><ambientLight intensity={.28}/></group>}
