-- The four Master roles replace the earlier placeholder roles. The distinct
-- Foundation Garden Steward path remains open as a non-Master field role.
UPDATE public.job_postings
SET status = 'closed'
WHERE slug IN ('music-producer-engineer', 'editor-manuscript-reader', 'presence-coordinator')
  AND status IN ('draft', 'open', 'paused');

INSERT INTO public.job_postings
  (title, slug, department, pillar, type, location, remote, compensation, description, responsibilities, requirements, nice_to_have, benefits, status, posted_date)
VALUES
  ('Master of Heart', 'master-of-heart', 'Presence', 'presence', 'part-time-to-full-time', 'Morongo Valley, CA · Remote OK', true, '$25/hr + Circle Access + Guild Membership', 'Presence is the Fire pillar: the circle that holds you. Weekly gatherings. Monthly retreats. Rites of passage. No hierarchy. No guru. Just belonging. The Master of Heart tends the flame—not by leading it, but by keeping it lit.', ARRAY['Facilitate weekly Whole Body Circles','Coordinate seasonal retreats and rites of passage ceremonies','Manage member onboarding and circle integration','Build ritual and ceremony frameworks for new gatherings','Support members in conflict resolution and circle health','Maintain the Presence calendar and event logistics','Serve as point person for Presence pillar inquiries'], ARRAY['3+ years facilitating groups, circles, or communities','Deep comfort with group dynamics and emotional field work','Training in nonviolent communication or similar frameworks','Ability to hold silence as skillfully as speech','Written and verbal excellence','Commitment to the Feed First model','Personal somatic or contemplative practice'], ARRAY['Experience with IFS, Shadow Work, or depth psychology','Familiarity with Human Design, astrology, or related frameworks','Trauma-informed facilitation training','Local to Morongo Valley or the high desert','Intentional-community or retreat-center experience'], ARRAY['Free participation in all circles and retreats','Guild membership included','Annual retreat at the Tetrahedron Garden','Flexible hours','Direct connection to founder and leadership'], 'open', now()),
  ('Master of Wisdom', 'master-of-wisdom', 'Press', 'press', 'part-time-to-full-time', 'Remote', true, '$30/hr + Profit Share on Edited Volumes', 'Press is the Air pillar. Books are not commodities; they are technology. The Whole Body Series is five volumes and one operating system. The Master of Wisdom is the gatekeeper of that technology, ensuring every word serves the work.', ARRAY['Review manuscript submissions through the Press pipeline','Edit accepted manuscripts: developmental, structural, and line','Collaborate with authors on revision and refinement','Maintain the editorial calendar for Press releases','Uphold the Feed First standard in every publication','Curate reading paths and collections for the library','Support launch efforts and commission new aligned work'], ARRAY['3+ years professional editorial experience','Portfolio of published or edited work','Strong nonfiction, spiritual, or philosophical writing literacy','Meticulous attention to detail','Comfort with the Whole Body system or similar frameworks','Ability to give clear, direct feedback','Self-directed and deadline-driven'], ARRAY['Independent or small-press publishing experience','Familiarity with sacred geometry, somatics, or sovereignty work','Copyediting or typesetting background','Writing credits','Digital publishing experience: ePub, PDF, or print-on-demand'], ARRAY['Flexible remote schedule','Profit share on edited volumes','Guild membership included','Free Whole Body Series volumes','Access to the full Press backlist'], 'open', now()),
  ('Master of Law', 'master-of-law', 'Guardian', 'guardian', 'contract-to-full-time', 'Remote', true, '$80k-$110k + Equity Eligibility', 'Guardian is the Ether pillar: the shape that holds. Sovereign systems. Trust architecture. Asset protection. IP shielding. The Master of Law designs and maintains the structures that ensure what is built outlasts its builder.', ARRAY['Design and maintain trust structures','Oversee entity formation and maintenance','Draft and review Studios, Press, and partnership agreements','Manage intellectual-property portfolios','Ensure applicable regulatory compliance','Advise Guardian partners on legal architecture','Represent the Constellation in negotiations','Document systems for succession and transfer'], ARRAY['JD or equivalent legal training','5+ years in trusts, estates, business formation, or IP law','Experience with Wyoming DAPT and Nevada or Delaware entities','Fluency in sovereignty-oriented legal frameworks, with a clear distinction from anti-government extremism','Bar admission in at least one US state','Excellent written and verbal communication','Discretion with sensitive matters','Commitment to the Feed First model'], ARRAY['Cryptocurrency or digital-asset structuring experience','Whole Body system familiarity','International trust or offshore structuring experience','Estate-planning or wealth-preservation background','Creative-enterprise or startup experience'], ARRAY['100% IP retention on personal creative work','Equity eligibility after six months','Guild membership included','Annual retreat at the Tetrahedron Garden','Flexible remote schedule','Direct advisory role with founder'], 'open', now()),
  ('Master of Tribe', 'master-of-tribe', 'Operations', 'operations', 'part-time-to-full-time', 'Morongo Valley, CA · Remote OK', true, '$35/hr + Guild Membership + Profit Share', 'The Tribe is the network. The Constellation is a living system of creators, builders, and stewards. The Master of Tribe tends the connections between people—matching talent to opportunity, member to member, pillar to pillar. You are the keeper of the mesh.', ARRAY['Manage the Living Spiral talent-matching system','Coordinate introductions between members and partners','Track member engagement and participation metrics','Organize quarterly AMAs and virtual gatherings','Maintain the member directory and profile system','Process partnership referrals and Guardian applications','Support onboarding for new Guild members','Be connective tissue across all five pillars'], ARRAY['3+ years in operations, network management, or community administration','Exceptional organizational and communication skills','Comfort with spreadsheets, databases, Airtable, or Notion','Understanding of how networks function','Warm, welcoming presence with high standards','Ability to work across multiple projects','Commitment to the Feed First model'], ARRAY['Membership organization or guild experience','Whole Body system familiarity','Local to Morongo Valley or Southern California','HR, recruiting, or talent-management background','Digital-community platform experience'], ARRAY['Free participation in all circles and retreats','Guild membership included','Profit share on coordinated releases','Flexible hours','Tetrahedron Garden access','Network access to vetted partners','Work from anywhere'], 'open', now())
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  department = EXCLUDED.department,
  pillar = EXCLUDED.pillar,
  type = EXCLUDED.type,
  location = EXCLUDED.location,
  remote = EXCLUDED.remote,
  compensation = EXCLUDED.compensation,
  description = EXCLUDED.description,
  responsibilities = EXCLUDED.responsibilities,
  requirements = EXCLUDED.requirements,
  nice_to_have = EXCLUDED.nice_to_have,
  benefits = EXCLUDED.benefits,
  status = EXCLUDED.status,
  posted_date = EXCLUDED.posted_date,
  updated_at = now();
